name: Eslint

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: Run eslint on code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install eslint
        run: bun add eslint

      - name: Run eslint
        run: bun eslint . --ext .js,.jsx,.ts,.tsx
