name: Publish

on:
  push:
    tags:
      - "v*"

jobs:
  changelog:
    name: "Generate Changelog"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Generate Changelog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bunx changelogithub --no-group
        continue-on-error: true

  build:
    name: "Build"
    needs: [changelog]
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Setup Bun"
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: "Install Dependencies"
        run: bun install

      - name: "Build"
        run: bun build:bun

  publish-npm:
    name: "Publish: npm Registry"
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Setup Bun"
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: "Install Dependencies"
        run: bun install

      - name: "Publish"
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm publish --access=public --registry=https://registry.npmjs.org --no-git-checks
